"""add_page

Revision ID: 09e04de84e98
Revises: 56fa62a328fa
Create Date: 2025-03-13 12:43:30.242992

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '09e04de84e98'
down_revision = '56fa62a328fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    # ### end Alembic commands ###
