"""add edited_at

Revision ID: 1d606bc8f5ee
Revises: 702c543b90a0
Create Date: 2025-04-12 14:56:48.301838

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1d606bc8f5ee'
down_revision = '702c543b90a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('edited_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'edited_at')
    # ### end Alembic commands ###
