"""add edited_at

Revision ID: 1d606bc8f5ee
Revises: 702c543b90a0
Create Date: 2025-04-12 14:56:48.301838

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d606bc8f5ee'
down_revision = '702c543b90a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_index('pages_slug_uindex', table_name='pages')
    op.add_column('users', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('users', 'edited_at')
    op.create_index('pages_slug_uindex', 'pages', ['slug'], unique=True)
    op.alter_column('pages', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
