"""add_settings

Revision ID: 22f6d57cab03
Revises: 3bd498cba8c7
Create Date: 2025-04-10 15:52:32.426058

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '22f6d57cab03'
down_revision = '3bd498cba8c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
