"""Add slug to Page

Revision ID: 3bd498cba8c7
Revises: ae96902bd925
Create Date: 2025-04-06 14:22:19.741337

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3bd498cba8c7'
down_revision = 'ae96902bd925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('slug', sa.String(length=100), nullable=False))
    op.create_unique_constraint('pages_slug_uindex', 'pages', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'slug')
    # ### end Alembic commands ###
