"""Add slug to Page

Revision ID: 3bd498cba8c7
Revises: ae96902bd925
Create Date: 2025-04-06 14:22:19.741337

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bd498cba8c7'
down_revision = 'ae96902bd925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('pages', sa.Column('slug', sa.String(length=100), nullable=False))
    op.alter_column('pages', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'pages', ['slug'])
    op.alter_column('users', 'role',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'pages', type_='unique')
    op.alter_column('pages', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('pages', 'slug')
    op.drop_table('password_resets')
    op.drop_table('settings')
    # ### end Alembic commands ###
