"""seed_default_category

Revision ID: 40c4336daf2d
Revises: ed6043161f03
Create Date: 2025-04-12 18:27:52.115874

"""

import sqlalchemy as sa
from alembic import op
from db.orm import Category

# revision identifiers, used by Alembic.
revision = '40c4336daf2d'
down_revision = 'ed6043161f03'
branch_labels = None
depends_on = None

YEAR = 2025


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.insert(Category).values(
            title=f"{YEAR}"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.delete(Category).where(Category.title == f"{YEAR}"))
    # ### end Alembic commands ###
