"""longtext_html_content

Revision ID: 702c543b90a0
Revises: a2e712810de0
Create Date: 2025-04-11 19:36:13.978134

"""

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '702c543b90a0'
down_revision = 'a2e712810de0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'html_content',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'html_content',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
