"""fix title_column

Revision ID: a8dcc681f951
Revises: ae96902bd925
Create Date: 2025-03-29 12:36:00.239569

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8dcc681f951'
down_revision = 'ae96902bd925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'title',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'title',
               existing_type=sa.String(length=100),
               type_=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
