"""fix edited_at column

Revision ID: ae96902bd925
Revises: b77a60239c60
Create Date: 2025-03-29 12:30:46.484138

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae96902bd925'
down_revision = 'b77a60239c60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pages', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('pages', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.add_column('pages', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pages', 'categories', ['category_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=True))
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('users', 'user_email',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('users', 'user_password',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.alter_column('users', 'user_password',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)
    op.alter_column('users', 'user_email',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=35),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=35),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.drop_table('categories')
    # ### end Alembic commands ###
