"""cascade_permissions

Revision ID: b5a6b41ccd3d
Revises: f00c3edd8bd9
Create Date: 2025-05-28 13:09:28.229842

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = 'b5a6b41ccd3d'
down_revision = 'f00c3edd8bd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_category_permissions_ibfk_2', 'user_category_permissions', type_='foreignkey')
    op.drop_constraint('user_category_permissions_ibfk_1', 'user_category_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'user_category_permissions', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_category_permissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_page_permissions_ibfk_1', 'user_page_permissions', type_='foreignkey')
    op.drop_constraint('user_page_permissions_ibfk_2', 'user_page_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'user_page_permissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_page_permissions', 'pages', ['page_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_page_permissions_ibfk_1', 'user_page_permissions', type_='foreignkey')
    op.drop_constraint('user_page_permissions_ibfk_2', 'user_page_permissions', type_='foreignkey')
    op.create_foreign_key('user_page_permissions_ibfk_2', 'user_page_permissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_page_permissions_ibfk_1', 'user_page_permissions', 'pages', ['page_id'], ['id'])
    op.drop_constraint('user_category_permissions_ibfk_1', 'user_category_permissions', type_='foreignkey')
    op.drop_constraint('user_category_permissions_ibfk_2', 'user_category_permissions', type_='foreignkey')
    op.create_foreign_key('user_category_permissions_ibfk_1', 'user_category_permissions', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('user_category_permissions_ibfk_2', 'user_category_permissions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
