"""add_user_profile_fields

Revision ID: e73677806d08
Revises: 40c4336daf2d
Create Date: 2025-04-26 12:37:22.018500

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'e73677806d08'
down_revision = '40c4336daf2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('title_before_name', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('title_after_name', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('middle_name', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'title_after_name')
    op.drop_column('users', 'title_before_name')
    # ### end Alembic commands ###
