"""alter_columns

Revision ID: ed6043161f03
Revises: 1d606bc8f5ee
Create Date: 2025-04-12 18:23:04.326609

"""

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed6043161f03'
down_revision = '1d606bc8f5ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_index('pages_slug_uindex', table_name='pages')

    # set all NULL roles to 0 (user)
    op.execute("UPDATE users SET role = 0 WHERE role IS NULL;")
    op.alter_column('users', 'role',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index('pages_slug_uindex', 'pages', ['slug'], unique=True)
    op.alter_column('pages', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
