"""alter_user_role

Revision ID: ee8cd892ede8
Revises: 39cf298c4f28
Create Date: 2025-04-09 12:35:20.637822

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee8cd892ede8'
down_revision = '39cf298c4f28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Použije sa pri `alembic upgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Použije sa pri `alembic downgrade ...`."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('pages', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
